== RxJava 3 API

=== Setting up with an Rxified router

To handle GraphQL requests on a Rxified {@link io.vertx.rxjava3.ext.web.Route}, make sure to import the {@link io.vertx.rxjava3.ext.web.handler.graphql.GraphQLHandler} class.

=== Working with Vert.x Rxified APIs

GraphQL-Java expects `CompletionStage` for asynchronous results in data fetchers and batch loaders.

Therefore, if you work with the Vert.x Rxified APIs (e.g. the https://vertx.io/docs/vertx-web-client/java/#_rxjava_3_api[Web Client]), you will have to adapt the `Single` and `Maybe` objects.

[source,java]
----
DataFetcher<CompletionStage<String>> fetcher = environment -> {
  Single<String> data = loadDataFromBackend();
  return data.toCompletionStage();
};
----

[TIP]
====
Instead of converting `Single` or `Maybe` to `CompletionStage` manually in every data fetcher implementation, configure GraphQL-Java with the {@link io.vertx.rxjava3.ext.web.handler.graphql.instrumentation.SingleAdapter} and {@link io.vertx.rxjava3.ext.web.handler.graphql.instrumentation.MaybeAdapter} https://www.graphql-java.com/documentation/instrumentation/[instrumentations].

First, declare the instrumentations while configuring GraphQL-Java.

[source,$lang]
----
{@link examples.RxWebGraphQLExamples#singleAndMaybeAdapters}
----

Then you can return `Single` or `Maybe` directly.

[source,$lang]
----
{@link examples.RxWebGraphQLExamples#singleDataFetcher}
----
====
