ifdef::java[]
== RxJava API

The RxJava {@link io.vertx.rxjava.ext.web.client.HttpRequest} provides an rx-ified version of the original API,
the {@link io.vertx.rxjava.ext.web.client.HttpRequest#rxSend()} method returns a `Single<HttpResponse<Buffer>>` that
makes the HTTP request upon subscription, as consequence, the {@code Single} can be subscribed many times.

[source,$lang]
----
{@link examples.RxWebClientExamples#simpleGet(io.vertx.rxjava.ext.web.client.WebClient)}
----

The obtained {@code Single} can be composed and chained naturally with the RxJava API

[source,$lang]
----
{@link examples.RxWebClientExamples#flatMap(io.vertx.rxjava.ext.web.client.WebClient)}
----

The same APIs are available

[source,$lang]
----
{@link examples.RxWebClientExamples#moreComplex(io.vertx.rxjava.ext.web.client.WebClient)}
----

The {@link io.vertx.rxjava.ext.web.client.HttpRequest#sendStream(rx.Observable, io.vertx.core.Handler)} shall
be preferred for sending bodies {@code Observable<Buffer>}

[source,$lang]
----
{@link examples.RxWebClientExamples#sendObservable(io.vertx.rxjava.ext.web.client.WebClient)}
----

Upon subscription, the {@code body} will be subscribed and its content used for the request.

=== Error Handling

The RxJava version of the WebClient does not automatically consider request/server errors (4XX/5XX) as
errors for the purpose of `onError` handlers. In order to handle errors of this kind, you need to `map`
the response to an Exception like this:

[source,$lang]
----
{@link examples.RxWebClientExamples#mapToError(io.vertx.rxjava.ext.web.client.HttpResponse)}
----

And then, you can use Rx-ified error handling like this:

[source,$lang]
----
{@link examples.RxWebClientExamples#rxErrorHandlingExample(io.vertx.rxjava.ext.web.client.WebClient)}
----
endif::[]


